### ISSUE TITLE
Can't call "health" check

### ISSUE THREAD

**Issue by davoult** [eric-belhomme/nagios_check_dell_s_series#2]
Hi Eric,

When i trying to execute "health" check on  *Dell EMC Networking OS10 Enterprise S4128F-ON*, I have the following error:

```
./check_dell_s_series.py -H 10.8.100.241 -C eon@DCC2012! -m health
Traceback (most recent call last):
  File "./check_dell_s_series.py", line 277, in <module>
    retCode = getSystemInfo()
  File "./check_dell_s_series.py", line 139, in getSystemInfo
    message.append('chassis: ' + Os10ChassisDefType.get(vals[0]) + ' (rev. ' + vals[1] + ') - p/n:' + vals[2] + ' - ServiceTag:' + vals[3])
TypeError: cannot concatenate 'str' and 'NoneType' objects
```
On other hand, all other checks work's well.
Do you have some idea ?

Sébastien,

**Comment by lboue** [comment]
Hello Sébastien,

You can see the issue #1. 

Ludovic

**Comment by eric-belhomme** [comment]
Hello Sebastien,
As stated by lboue, this was fixed thannks to him. I merged into master just right now.
Also, Laurent Belgrain directly reported the same kind of issues with OIDs .1.3.6.1.4.1.674.11000.5000.100.4.1.1.3.1 and .1.3.6.1.4.1.674.11000.5000.100.4.1.1.4.1 (respectively lines 133 and 145).
I also fixed this. I hope this will not introduce regression...

Regards,

Eric
